# Testing sample object created in function
cities = [{
                'city': 'San Antonio',
                'location': [29.5, -98.5],  
                'perc_asian': '2.4',
                'perc_black': '6.9',
                'perc_latino': '62',
                'spotify_url': 'http://everynoise.com/everyplace.cgi?root=San%20Antonio%20Texas%20US&scope=United%20States',
                'top_5_artists': [],
                'top_artists': [
                                {'artist': 'Bobby Pulido',
                                'tracks': ['spotify:track:1tg7ZzCAkjDNENdWL7WuIr',
                                    'spotify:track:2JJSGhPpATm8lXeYjD95fw',
                                    'spotify:track:5iuGn3RXvfvHIyIe8fyxBE']
                                },
                                {'artist': 'Z-Ro',
                                'tracks': ['spotify:track:338VhnERUjSnXmIFGuxonu',
                                    'spotify:track:62XoIh6od0W79r8Tk51VOp',
                                    'spotify:track:1uAmSjg1c8JLzkWlZS2yWQ']},
                                {'artist': 'Josh Abbott Band',
                                'tracks': ['spotify:track:7dPLFIBvafAXkJF7eDRcIs',
                                    'spotify:track:0wcDu6p0q2OjbzOltoiRMN',
                                    'spotify:track:7k0ahlHosIWblaaIsEqJ8M']},
                                {'artist': 'Solido',
                                'tracks': ['spotify:track:2rtWElTrFeycfkybYyou0e',
                                    'spotify:track:26sglkAhF4WfzcigwRJwL9',
                                    'spotify:track:727yvKyuB1XJaNoV2XNOCR']},
                                {'artist': 'Costumbre',
                                'tracks': ['spotify:track:3fW0JzqjeUNpMCdxy1AcUP',
                                    'spotify:track:41rJ9FmSJ2pV5SIitwDvdu',
                                    'spotify:track:6FxXIsFtYEZdh9qLFNvQc4']},
                                {'artist': 'Randy Rogers Band',
                                'tracks': ['spotify:track:4hFSl2YfBUCY7RgZ8OhwCO',
                                    'spotify:track:1EHNNWLiWe1PJADKEnMvIr',
                                    'spotify:track:3bZKIfJVpW8HktEafRnRP2']},
                                {'artist': 'South Park Mexican',
                                'tracks': ['spotify:track:45tI2PP1M7hhqhdNRz0YAn',
                                    'spotify:track:0Z6iHJRVx00MOwXGl5ku4i',
                                    'spotify:track:0zRpsXMbE1oBv58A22BhKN']},
                                {'artist': 'Ramon Ayala Y Sus Bravos Del Norte',
                                'tracks': ['spotify:track:7ENNmSQQajwKTPX0m7ejYA',
                                    'spotify:track:34HiQ9eroaoXlS4b5ZJQWh',
                                    'spotify:track:7o2QFKNjFDRzGDPvSYH6pn']},
                                {'artist': 'Mazz',
                                'tracks': ['spotify:track:5TMB9Xnfe1lbvDHZtjCUcZ',
                                    'spotify:track:4ITL0FFTc4LRFyvUVeY4CC',
                                    'spotify:track:5DGCz0pG9SrJpIps43xyod']},
                                {'artist': 'Grupo Pegasso',
                                'tracks': ['spotify:track:2Wd53oIqGVC5Vyd5R96l4J',
                                    'spotify:track:7hUeM605R3peXzGU9FBgix',
                                    'spotify:track:3V29kIVkcNchC5ydvY0ZyR']},
                                {'artist': 'Siggno',
                                'tracks': ['spotify:track:5f9iiJV4M4FmPbIGtxwoeM',
                                    'spotify:track:31jvfOIBsOLYaT5YHQS4J8',
                                    'spotify:track:0eVpwKZw9vYNF9gAU7AUqq']},
                                {'artist': 'Blake',
                                'tracks': ['spotify:track:1nNSyLtQazJ4oGbBiPa2xx',
                                    'spotify:track:4nlCHsRRCrnIzuRbKGT75W',
                                    'spotify:track:5eV4w3EUAxxdbD6ezQ29bN']},
                                {'artist': 'George Strait',
                                'tracks': ['spotify:track:4sDiJmHNcm0wLTH8ns65va',
                                    'spotify:track:3ZJb4Qn1TvHx3HW08YLmTR',
                                    'spotify:track:0J3AaAp2XKLhfvNNYE6iie']},
                                {'artist': 'Duelo',
                                'tracks': ['spotify:track:2cBzuJhVILqkpFAYxHwm64',
                                    'spotify:track:37BWywucpTcrzdhcZwkKyG',
                                    'spotify:track:2jFeVaKwofd1mVk50xSzjg']},
                                {'artist': 'Los Invasores De Nuevo León',
                                'tracks': ['spotify:track:29m95um0i0NThLbWA765Lg',
                                    'spotify:track:2Tq1NVRQwWSZ0CUSxU0cFA',
                                    'spotify:track:7a5msYrIHJ1bx7pTLKVbZ9']},
                                {'artist': 'Cody Johnson',
                                'tracks': ['spotify:track:2g3vpJiqwswGJbUOSkCWqC',
                                    'spotify:track:4EETgKkkLxXrsrc0q50K1P',
                                    'spotify:track:5EDt7cxNUAVK0QlGjPo1dZ']}
                            ],
                'top_track': '',
                'track_ids': ['spotify:track:2wtaarbpkeVMppRu0zeN7s',
                                'spotify:track:4hFSl2YfBUCY7RgZ8OhwCO',
                                'spotify:track:61RtRacZsYYxUFSLaSBeou',
                                'spotify:track:7Dod4VT1f76b5sekRUXGPN',
                                'spotify:track:5f9iiJV4M4FmPbIGtxwoeM',
                                'spotify:track:1EHNNWLiWe1PJADKEnMvIr',
                                'spotify:track:3bZKIfJVpW8HktEafRnRP2',
                                'spotify:track:5TMB9Xnfe1lbvDHZtjCUcZ',
                                'spotify:track:3lDMZAwtuSEUB0Sxkn7qrQ',
                                'spotify:track:1hTVjihLZcyCWIkT3MEC2L',
                                'spotify:track:12M7VICbjYKBeIMObErGNS',
                                'spotify:track:31jvfOIBsOLYaT5YHQS4J8',
                                'spotify:track:0eVpwKZw9vYNF9gAU7AUqq',
                                'spotify:track:4ITL0FFTc4LRFyvUVeY4CC',
                                'spotify:track:6RlsRsjrJNZRqwgIDgeXY1',
                                'spotify:track:45tI2PP1M7hhqhdNRz0YAn',
                                'spotify:track:7dPLFIBvafAXkJF7eDRcIs',
                                'spotify:track:2rtWElTrFeycfkybYyou0e',
                                'spotify:track:3RXoiN0V2UpFLvR0bfAZn5',
                                'spotify:track:338VhnERUjSnXmIFGuxonu',
                                'spotify:track:26sglkAhF4WfzcigwRJwL9',
                                'spotify:track:62XoIh6od0W79r8Tk51VOp',
                                'spotify:track:4w82HB9FEvykpSUB1BOfUH',
                                'spotify:track:1uAmSjg1c8JLzkWlZS2yWQ',
                                'spotify:track:6a5hgfa4rkHqYWaW2kgwJ3',
                                'spotify:track:5DGCz0pG9SrJpIps43xyod',
                                'spotify:track:0Z6iHJRVx00MOwXGl5ku4i',
                                'spotify:track:6zUyBt2qT4KP7zAdHjZgqO',
                                'spotify:track:0wcDu6p0q2OjbzOltoiRMN',
                                'spotify:track:2cBzuJhVILqkpFAYxHwm64',
                                'spotify:track:7k0ahlHosIWblaaIsEqJ8M',
                                'spotify:track:2Wd53oIqGVC5Vyd5R96l4J',
                                'spotify:track:0zRpsXMbE1oBv58A22BhKN',
                                'spotify:track:4sDiJmHNcm0wLTH8ns65va',
                                'spotify:track:4LieLlRVOkdKbjrj3seQ44',
                                'spotify:track:37BWywucpTcrzdhcZwkKyG',
                                'spotify:track:2jFeVaKwofd1mVk50xSzjg',
                                'spotify:track:7hUeM605R3peXzGU9FBgix',
                                'spotify:track:3JJ3RegwBPhDSbhZlt9sCh',
                                'spotify:track:3V29kIVkcNchC5ydvY0ZyR',
                                'spotify:track:1Dd7dAgpbNS0nDzVPAT275',
                                'spotify:track:3hUXBzW8zP2koWrxG5fNeL',
                                'spotify:track:1nNSyLtQazJ4oGbBiPa2xx',
                                'spotify:track:727yvKyuB1XJaNoV2XNOCR',
                                'spotify:track:4nlCHsRRCrnIzuRbKGT75W',
                                'spotify:track:4edZCE9G5hMfScEpLNZqFL',
                                'spotify:track:16NRutjxxtfqIDvlwLFw1A',
                                'spotify:track:7kkOuhyWcINZMDh4QGVyMB',
                                'spotify:track:7ENNmSQQajwKTPX0m7ejYA',
                                'spotify:track:5i0n3xtjuVFLp646joI9XS',
                                'spotify:track:1idB3b2IIfal1DPwOuDQwo',
                                'spotify:track:12TE7Vt592RcM1G3EaaZ0f',
                                'spotify:track:53lnXxETBx3eRxFG30F3v1',
                                'spotify:track:5eV4w3EUAxxdbD6ezQ29bN',
                                'spotify:track:3fW0JzqjeUNpMCdxy1AcUP',
                                'spotify:track:0NZtpFRzI4ZygqISV7fTtD',
                                'spotify:track:7Jdo0Ivw7rFvKwOmjBJ0z1',
                                'spotify:track:4R04Mu4CANunY7VQdhBLU9',
                                'spotify:track:2g3vpJiqwswGJbUOSkCWqC',
                                'spotify:track:4EETgKkkLxXrsrc0q50K1P',
                                'spotify:track:2ZCG2fdMvFM2yv2MwhUJKL',
                                'spotify:track:41rJ9FmSJ2pV5SIitwDvdu',
                                'spotify:track:3HkMNtOIciULbIrsxyl1mq',
                                'spotify:track:5EDt7cxNUAVK0QlGjPo1dZ',
                                'spotify:track:1tg7ZzCAkjDNENdWL7WuIr',
                                'spotify:track:3ZJb4Qn1TvHx3HW08YLmTR',
                                'spotify:track:3DcmMHy3mvNC4K9tx5M3Nk',
                                'spotify:track:6FxXIsFtYEZdh9qLFNvQc4',
                                'spotify:track:34HiQ9eroaoXlS4b5ZJQWh',
                                'spotify:track:702RdmOBmeHXG2jAmNeGN8',
                                'spotify:track:3tQnH83OR5LgMkPqGrnZo5',
                                'spotify:track:2RPRHTcZoWLtFY3xJ00CYQ',
                                'spotify:track:2cUR2tZlH6fAlNpIjZ9RlQ',
                                'spotify:track:29m95um0i0NThLbWA765Lg',
                                'spotify:track:0J3AaAp2XKLhfvNNYE6iie',
                                'spotify:track:3IeCV02kKK8OlbtrKL1h7K',
                                'spotify:track:5ZlPmjDhZi1qQWVHiaU7MU',
                                'spotify:track:3OoTWhcb1NL1R1aop3An2H',
                                'spotify:track:1spvvISCt2fPLjCWT25Oi9',
                                'spotify:track:7o2QFKNjFDRzGDPvSYH6pn',
                                'spotify:track:406qqOwEMlBUUugyHXBy8B',
                                'spotify:track:7AM7gEehnVqElO1BD9h8dC',
                                'spotify:track:2JJSGhPpATm8lXeYjD95fw',
                                'spotify:track:6RWa1cOsOnefCnV6mzPprB',
                                'spotify:track:5o4hMBr9ovkytff8TBHreg',
                                'spotify:track:21YACJjPs7xR9JcgCHspDb',
                                'spotify:track:5iuGn3RXvfvHIyIe8fyxBE',
                                'spotify:track:6TefPQD0oc88BNALpu4U87',
                                'spotify:track:28Sc21lrWcZD9Ov4rRkPJq',
                                'spotify:track:3KdOm1GJJWYDTQmIbRIkcL',
                                'spotify:track:5ngtOXQLLcE0LXUUe4xwQh',
                                'spotify:track:59rtiYOPgMEDf3yPEfU2la',
                                'spotify:track:24PWKmemCvqfyVXODhoKHW',
                                'spotify:track:3b9FS4tWpy63wsBHYQ5Lmq',
                                'spotify:track:1MvuU0panHMv0CcAFC1Omr',
                                'spotify:track:2Tq1NVRQwWSZ0CUSxU0cFA',
                                'spotify:track:6EUEnvlcNhfkWhZFy0GZI5',
                                'spotify:track:1vBpwxsLVwaR4evBIaFmqD',
                                'spotify:track:7a5msYrIHJ1bx7pTLKVbZ9',
                                'spotify:track:6lEIjrQNwJPecJ7mMXjhjo']
            }
]